/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto;

import java.util.*;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Ferna
 */
public class projeto extends javax.swing.JFrame {

    Integer contador = 0;

    Double mediaCpu = 0.0, mediaDisco = 0.0, mediaMemoria = 0.0;
    Integer minCpu = 100, minMemoria = 100, minDisco = 100;
    Integer maxCpu = 0, maxMemoria = 0, maxDisco = 0;

    /**
     * Creates new form projeto
     */
    public projeto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblValorMaxCpu1 = new javax.swing.JLabel();
        barCpu1 = new javax.swing.JProgressBar();
        lblValorMediaCpu1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblValorMedioCpu1 = new javax.swing.JLabel();
        lblValorMinCpu1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barDisco = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        barCpu = new javax.swing.JProgressBar();
        barMemoria = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblValorMediaCpu = new javax.swing.JLabel();
        lblValorMaxCpu = new javax.swing.JLabel();
        lblValorMinCpu = new javax.swing.JLabel();
        lblValorMedioCpu = new javax.swing.JLabel();
        lblValorAtualCpu = new javax.swing.JLabel();
        lblValorMaxDisco = new javax.swing.JLabel();
        lblValorMinDisco = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblValorMedioDisco = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblValorMediaCpu2 = new javax.swing.JLabel();
        lblValorAtualDisco = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblValorMedioMemoria = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblValorMediaCpu3 = new javax.swing.JLabel();
        lblValorMaxMemoria = new javax.swing.JLabel();
        lblValorMinMemoria = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblValorAtualMemoria = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        jLabel8.setText("jLabel8");

        lblValorMaxCpu1.setText("0");

        lblValorMediaCpu1.setText("Media");

        jLabel7.setText("Max");

        lblValorMedioCpu1.setText("0");

        lblValorMinCpu1.setText("0");

        jLabel11.setText("Min");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPU");

        jButton1.setText("Monitorar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Disco");

        jLabel3.setText("Memoria");

        jLabel4.setText("Max");

        jLabel5.setText("Min");

        jLabel6.setText("Atual");

        lblValorMediaCpu.setText("Media");

        lblValorMaxCpu.setText("0");

        lblValorMinCpu.setText("0");

        lblValorMedioCpu.setText("0");

        lblValorAtualCpu.setText("0");

        lblValorMaxDisco.setText("0");

        lblValorMinDisco.setText("0");

        jLabel12.setText("Max");

        lblValorMedioDisco.setText("0");

        jLabel13.setText("Min");

        lblValorMediaCpu2.setText("Media");

        lblValorAtualDisco.setText("0");

        jLabel14.setText("Atual");

        lblValorMedioMemoria.setText("0");

        jLabel15.setText("Min");

        lblValorMediaCpu3.setText("Media");

        lblValorMaxMemoria.setText("0");

        lblValorMinMemoria.setText("0");

        jLabel16.setText("Max");

        lblValorAtualMemoria.setText("0");

        jLabel17.setText("Atual");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorMinMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(lblValorMediaCpu3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorMedioMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblValorMaxMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(barCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(barDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblValorMinCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(61, 61, 61)
                                                    .addComponent(lblValorMediaCpu)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblValorMedioCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblValorAtualCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblValorMaxCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblValorAtualDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblValorMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61)
                                            .addComponent(lblValorMediaCpu2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblValorMedioDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblValorAtualMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblValorMaxDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(lblValorAtualCpu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblValorMediaCpu)
                    .addComponent(lblValorMinCpu)
                    .addComponent(lblValorMedioCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lblValorMaxCpu))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(lblValorAtualDisco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblValorMediaCpu2)
                    .addComponent(lblValorMinDisco)
                    .addComponent(lblValorMedioDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(lblValorMaxDisco))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblValorAtualMemoria)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblValorMediaCpu3)
                    .addComponent(lblValorMinMemoria)
                    .addComponent(lblValorMedioMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(lblValorMaxMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Random rand = new Random();
        Integer pgCpu, pgDisco, pgMemoria;
        Double mediaMemoria1, mediaDisco1, mediaCpu1;
        contador++;

        pgCpu = rand.nextInt(101);
        pgDisco = rand.nextInt(101);
        pgMemoria = rand.nextInt(101);

        if (pgCpu < minCpu) {
            minCpu = pgCpu;
        }

        if (pgDisco < minDisco) {
            minDisco = pgDisco;
        }

        if (pgMemoria < minMemoria) {
            minMemoria = pgMemoria;
        }
        
        if (pgCpu > maxCpu) {
            maxCpu = pgCpu;
        }

        if (pgDisco > maxDisco) {
            maxDisco = pgDisco;
        }

        if (pgMemoria > maxMemoria) {
            maxMemoria = pgMemoria;
        }
        
        mediaMemoria = (mediaMemoria + pgMemoria);
        mediaMemoria1 = (mediaMemoria / contador);
        
        mediaDisco = (mediaDisco + pgDisco);
        mediaDisco1 = (mediaDisco / contador);
        
        mediaCpu = (mediaCpu + pgCpu);
        mediaCpu1 = (mediaCpu / contador);
        
        lblValorMinCpu.setText(String.valueOf(minCpu));
        lblValorMaxCpu.setText(String.valueOf(maxCpu));
        lblValorMedioCpu.setText(String.valueOf(mediaCpu1));
        lblValorAtualCpu.setText(String.valueOf(pgCpu));
        
        lblValorMinMemoria.setText(String.valueOf(minMemoria));
        lblValorMaxMemoria.setText(String.valueOf(maxMemoria));
        lblValorMedioMemoria.setText(String.valueOf(mediaMemoria1));
        lblValorAtualMemoria.setText(String.valueOf(pgMemoria));
        
        lblValorMinDisco.setText(String.valueOf(minDisco));
        lblValorMaxDisco.setText(String.valueOf(maxDisco));
        lblValorMedioDisco.setText(String.valueOf(mediaDisco1));
        lblValorAtualDisco.setText(String.valueOf(pgDisco));
        

        barCpu.setValue(pgCpu);
        barDisco.setValue(pgDisco);
        barMemoria.setValue(pgMemoria);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(projeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(projeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(projeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(projeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new projeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barCpu;
    private javax.swing.JProgressBar barCpu1;
    private javax.swing.JProgressBar barDisco;
    private javax.swing.JProgressBar barMemoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblValorAtualCpu;
    private javax.swing.JLabel lblValorAtualDisco;
    private javax.swing.JLabel lblValorAtualMemoria;
    private javax.swing.JLabel lblValorMaxCpu;
    private javax.swing.JLabel lblValorMaxCpu1;
    private javax.swing.JLabel lblValorMaxDisco;
    private javax.swing.JLabel lblValorMaxMemoria;
    private javax.swing.JLabel lblValorMediaCpu;
    private javax.swing.JLabel lblValorMediaCpu1;
    private javax.swing.JLabel lblValorMediaCpu2;
    private javax.swing.JLabel lblValorMediaCpu3;
    private javax.swing.JLabel lblValorMedioCpu;
    private javax.swing.JLabel lblValorMedioCpu1;
    private javax.swing.JLabel lblValorMedioDisco;
    private javax.swing.JLabel lblValorMedioMemoria;
    private javax.swing.JLabel lblValorMinCpu;
    private javax.swing.JLabel lblValorMinCpu1;
    private javax.swing.JLabel lblValorMinDisco;
    private javax.swing.JLabel lblValorMinMemoria;
    // End of variables declaration//GEN-END:variables
}
